<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<script>
  /**
   * 3.1 错误的类型
   * Error    所有错误的父类型
   * ReferenceError    引用的变量不存在
   * TypeError    数据类型不正确
   * RangeError：数据值不在其允许的范围内 死循环
   * SyntaxError    语法错误
   * 3.2 错误处理
   * 捕获错误：try{ }catch( ){ }
   * 3.3 错误对象
   *  message 属性：错误相关信息。
   *  stack 属性：记录信息
   * */
  //演示：ReferenceError    引用的变量不存在
 // console.log(a);
  //TypeError    数据类型不正确
  // const demo=()=>{}
  // console.log(demo());
  //RangeError：数据值不在其允许的范围内
  // const demo=()=>{demo()}
  // demo()
  /*
  * 如何捕获一个错误
  *     1.try中放可能出现错误的代码 一旦出现错误立即停止try中的代码执行 调用catc并携带错误信息
  *
  * */

 /* try{
      console.log(1);
      console.log(a);
      console.log(2)
  }catch (error) {
      console.log('catch被调用 错误的原因:'+error)
  }*/
  //如何抛出一个错误
  function demo() {
      const  date=Date.now()
      if (date%2===0){
          console.log('偶数 可以正常工作')
      }else{
          throw new Error('奇数 不能正常工作')
      }
  }
  try{
      demo()
  }catch (error){
      debugger
      console.log(error);
  }
</script>
</body>
</html>